{
 "title": "Mobile Services",
 "tags": [ "mobile-services" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resolutionInterval",
    "label": "Resolution",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Keycloak",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 14, "x": 0, "y": 1 },
     "content": "# Keycloak\n\nKeycloak is an open source Identity and Access Management solution aimed at modern applications and services. It makes it easy to secure applications and services with little to no code.\n\nFind out more at [keycloak.org](http://www.keycloak.org/)!\n\n"
    },
    {
     "title": "Provisioned",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "keycloak_info" }
     ]
    },
    {
     "title": "Version",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "keycloak_info" }
     ]
    },
    {
     "title": "Registrations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "sum(keycloak_registrations)" }
     ]
    },
    {
     "title": "Login Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(keycloak_failed_login_attempts)"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 14, "x": 0, "y": 2 },
     "content": "# Data Synchronization\n\nSync mobile data synchronization framework allows Sync Apps to seamessly continue working when the network conection is lost, and allows them to recover when the network connection is restored.\n\nFind out more at [feedhenry.org](http://feedhenry.org/projects/#data-synchronization)!"
    },
    {
     "title": "Provisioned",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 14, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "nodejs_version_info" }
     ]
    },
    {
     "title": "Version",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 18, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "nodejs_version_info" }
     ]
    },
    {
     "title": "Active requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nodejs_active_requests_total" }
     ]
    },
    {
     "title": "Lag of event loop",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nodejs_eventloop_lag_seconds" }
     ]
    }
   ]
  },
  {
   "title": "Mobile app metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 3 },
     "content": "# Mobile App Metrics\n\nMobile App Metrics service provides analytics about the mobile apps installed on user devices.\n\nFind out more at [project website](https://github.com/aerogear/aerogear-metrics-api/)."
    },
    {
     "title": "Unique clients",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  count(distinct latestEntryInTimeRange.clientId)\nFROM\n    (select entry.clientId, entry.event_time, entry.data \n      from mobileAppMetrics entry \n      inner join \n        (select clientId, max(event_time) as latestEntryTime \n          from mobileAppMetrics \n          where $__timeFilter(event_time) and event_type='init'\n          group by clientId\n        ) \n        latestEntry \n        on entry.clientId = latestEntry.clientId and entry.event_time = latestEntryTime\n        WHERE event_type='init'\n      ) latestEntryInTimeRange;"
      }
     ]
    },
    {
     "title": "App launches",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT count(*)\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='init';"
      }
     ]
    },
    {
     "title": "Apps",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  count(distinct data->'app'->>'appId')\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time) \n    AND data->'app' ? 'appId'\n    AND event_type='init';"
      }
     ]
    },
    {
     "title": "Unique clients per app",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time,\n  count(latestEntryInTimeRange.clientId),\n  (latestEntryInTimeRange.data->'app'->>'appId')::text as metric\nFROM\n    (select entry.clientId, entry.event_time, entry.data \n      from mobileAppMetrics entry \n      inner join \n        (select clientId, data->'app'->>'appId' as appId, max(event_time) as latestEntryTime \n          from mobileAppMetrics \n          where $__timeFilter(event_time) \n            AND data->'app' ? 'appId'\n            AND event_type='init'\n          group by clientId, appId\n        ) \n        latestEntry \n        on entry.clientId = latestEntry.clientId and entry.data->'app'->>'appId' = latestEntry.appId and entry.event_time = latestEntryTime\n        WHERE event_type='init'\n      ) latestEntryInTimeRange\n  where latestEntryInTimeRange.data->'app' ? 'appId'\n  GROUP by latestEntryInTimeRange.data->'app'->>'appId'\n  ORDER by latestEntryInTimeRange.data->'app'->>'appId';"
      }
     ]
    },
    {
     "title": "Unique clients per platform",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 7, "x": 8, "y": 7 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time,\n  count(latestEntryInTimeRange.clientId),\n  (latestEntryInTimeRange.data->'device'->>'platform')::text as metric\nFROM\n    (select entry.clientId, entry.event_time, entry.data \n      from mobileAppMetrics entry \n      inner join \n        (select clientId, max(event_time) as latestEntryTime \n          from mobileAppMetrics \n          where $__timeFilter(event_time)\n            AND event_type='init'\n          group by clientId\n        ) \n        latestEntry \n        on entry.clientId = latestEntry.clientId and entry.event_time = latestEntryTime\n        WHERE event_type='init'\n      ) latestEntryInTimeRange\n  where latestEntryInTimeRange.data->'device' ? 'platform'\n  GROUP by latestEntryInTimeRange.data->'device'->>'platform'\n  ORDER by latestEntryInTimeRange.data->'device'->>'platform';"
      }
     ]
    },
    {
     "title": "Unique clients per sdk version",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 7, "x": 15, "y": 7 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  now() as time,\n  count(latestEntryInTimeRange.clientId),\n  (latestEntryInTimeRange.data->'app'->>'sdkVersion')::text as metric\nFROM\n    (select entry.clientId, entry.event_time, entry.data \n      from mobileAppMetrics entry \n      inner join \n        (select clientId, max(event_time) as latestEntryTime \n          from mobileAppMetrics \n          where $__timeFilter(event_time)\n            AND event_type='init'\n          group by clientId\n        ) \n        latestEntry \n        on entry.clientId = latestEntry.clientId and entry.event_time = latestEntryTime\n        WHERE event_type='init'\n      ) latestEntryInTimeRange\n  where latestEntryInTimeRange.data->'app' ? 'sdkVersion'\n  GROUP by latestEntryInTimeRange.data->'app'->>'sdkVersion'\n  ORDER by latestEntryInTimeRange.data->'app'->>'sdkVersion';"
      }
     ]
    }
   ]
  },
  { "title": "Mobile security metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "content": "# Mobile Security Metrics\n\nGraphs here show Self-Defence Security Check results.\n\n"
  },
  {
   "title": "Passed check %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(passed)/sum(total) * 100 as perc_passed from (\n  SELECT (select sum(case when (sec->>'passed')::boolean then 1 else 0 end)\n  from jsonb_array_elements(data->'security') as sec) as passed,\n  jsonb_array_length(data->'security') as total\n  FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n) as totals\n"
    }
   ]
  },
  {
   "title": "Check count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(check_count) as value\nFROM (\n    SELECT jsonb_array_length(s.data->'security') as check_count\n    FROM mobileAppMetrics as s\n    WHERE $__timeFilter(s.event_time)\n      AND event_type='security'\n      AND data ? 'security'\n  ) AS check_totals"
    }
   ]
  },
  {
   "title": "Unique clients with checks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(clientId)\nFROM mobileAppMetrics\nWHERE $__timeFilter(event_time)\n  AND event_type='security'\n  AND data ? 'security';"
    }
   ]
  },
  {
   "title": "Apps with checks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT data->'app'->>'appId')\n  FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n      AND event_type='security'\n      AND data ? 'security'\n      AND data ? 'app' AND data->'app' ? 'appId';"
    }
   ]
  },
  {
   "title": "Fails per check type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  checks.entry->>'name' as checkName,\n  count(*)\nFROM\n(\n  SELECT jsonb_array_elements(data->'security') as entry \n    FROM mobileAppMetrics \n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n) as checks\nWHERE checks.entry->>'passed' = 'false'\nGROUP BY checkName;"
    }
   ]
  },
  {
   "title": "Fails per app",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT now() as time, appId, sum(failed)\n  FROM\n  (SELECT\n    data->'app'->>'appId' as appId,\n    (select sum(case when (sec->>'passed')::boolean then 0 else 1 end) from jsonb_array_elements(data->'security') as sec) as failed\n    FROM mobileAppMetrics\n    WHERE $__timeFilter(event_time)\n      AND event_type='security'\n      AND data ? 'security'\n      AND data ? 'app' AND data->'app' ? 'appId') as fails\n  GROUP BY appId;"
    }
   ]
  },
  {
   "title": "Fails per platform",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT now() as time, platform, sum(failed)\n  FROM\n  (SELECT\n    data->'device'->>'platform' as platform,\n    (select sum(case when (sec->>'passed')::boolean then 0 else 1 end) from jsonb_array_elements(data->'security') as sec) as failed\n    FROM mobileAppMetrics\n    WHERE $__timeFilter(event_time)\n      AND event_type='security'\n      AND data ? 'security'\n      AND data ? 'device' AND data->'device' ? 'platform') as fails\n  GROUP BY platform;"
    }
   ]
  }
 ]
}