{
 "title": "Mobile app metrics",
 "tags": [ "mobile-app-metrics" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "appId",
    "label": "App",
    "query": "select distinct data->'app'->>'appId' from mobileappmetrics;"
   },
   {
    "name": "platform",
    "label": "Platform",
    "query": "select distinct data->'device'->>'platform' from mobileappmetrics;"
   },
   {
    "name": "resolutionInterval",
    "label": "Resolution",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "appMetricName", "label": "App Metric", "query": "sdkVersion, appVersion" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 1 },
   "content": "# Mobile app metrics\nThis dashboard shows metrics per app. \nSelect the app using the \"App\" dropdown above."
  },
  {
   "title": "Unique clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct latestEntryInTimeRange.clientId)\nFROM\n    (select entry.clientId, entry.event_time, entry.data \n      from mobileAppMetrics entry \n      inner join \n        (select clientId, data->'app'->>'appId' as appId, max(event_time) as latestEntryTime \n          from mobileAppMetrics \n          where $__timeFilter(event_time)\n            and event_type='init'\n            and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n            and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n          group by clientId, appId\n        ) \n        latestEntry \n        on entry.clientId = latestEntry.clientId and entry.data->'app'->>'appId' = latestEntry.appId and entry.event_time = latestEntryTime\n        where event_type='init'\n      ) latestEntryInTimeRange\n  where latestEntryInTimeRange.data->'app' ? 'appId';"
    }
   ]
  },
  {
   "title": "App launch count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    and event_type='init'\n    and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    and data->'device' ? 'platform' and data->'device'->>'platform' like $platform;"
    }
   ]
  },
  {
   "title": "Unique clients per platform",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(latestEntryInTimeRange.clientId),\n  (latestEntryInTimeRange.data->'device'->>'platform')::text as platform\nFROM\n    (select entry.clientId, entry.event_time, entry.data \n      from mobileAppMetrics entry \n      inner join \n        (select clientId, max(event_time) as latestEntryTime \n          from mobileAppMetrics \n          where $__timeFilter(event_time)\n            and event_type='init'\n          group by clientId\n        ) \n        latestEntry \n        on entry.clientId = latestEntry.clientId and entry.event_time = latestEntryTime\n        where event_type='init'\n      ) latestEntryInTimeRange\n  where latestEntryInTimeRange.data->'device' ? 'platform'\n  GROUP by platform;"
    }
   ]
  },
  {
   "title": "App launch count per platform",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(event_time,$resolutionInterval),\n  count(*),\n  (data->'device'->>'platform')::text as platform\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    and event_type='init'\n    and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  GROUP BY platform, time;"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(event_time,$resolutionInterval),\n  count(*),\n  'All Platforms' as metric\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    and event_type='init'\n    and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    and data->'device' ? 'platform'\n  GROUP BY time;"
    }
   ]
  },
  {
   "title": "Unique clients per platform version",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(latestEntryInTimeRange.clientId),\n  (data->'device'->>'platform')::text || ' ' || (data->'device'->>'platformVersion')::text as platformVersion\nFROM\n    (select entry.clientId, entry.event_time, entry.data \n      from mobileAppMetrics entry \n      inner join \n        (select clientId, max(event_time) as latestEntryTime \n          from mobileAppMetrics \n          where $__timeFilter(event_time)\n            and event_type='init'\n            and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n            and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n          group by clientId\n        ) \n        latestEntry \n        on entry.clientId = latestEntry.clientId and entry.event_time = latestEntryTime\n        where event_type='init'\n      ) latestEntryInTimeRange\n  GROUP by platformVersion;"
    }
   ]
  },
  {
   "title": "App launch count per platform version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(event_time,$resolutionInterval),\n  count(*),\n  (data->'device'->>'platform')::text || ' ' || (data->'device'->>'platformVersion')::text as platformVersion\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    and event_type='init'\n    and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  GROUP BY platformVersion, time;"
    }
   ]
  },
  {
   "title": "Metrics per $appMetricName [platform: $platform]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "appMetricName"
  },
  {
   "title": "Unique clients per $appMetricName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(latestEntryInTimeRange.clientId),\n  (latestEntryInTimeRange.data->'app'->>$appMetricName)::text as metric\nFROM\n    (select entry.clientId, entry.event_time, entry.data \n      from mobileAppMetrics entry \n      inner join \n        (select clientId, max(event_time) as latestEntryTime \n          from mobileAppMetrics \n          where $__timeFilter(event_time)\n            and event_type='init'\n            and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n            and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n          group by clientId\n        ) \n        latestEntry \n        on entry.clientId = latestEntry.clientId and entry.event_time = latestEntryTime\n        where event_type='init'\n      ) latestEntryInTimeRange\n  GROUP by metric;"
    }
   ]
  },
  {
   "title": "App launch count per $appMetricName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(event_time,$resolutionInterval),\n  count(*),\n  (data->'app'->>$appMetricName)::text as metric\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    and event_type='init'\n    and data->'app' ? $appMetricName\n    and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  GROUP BY metric, time;"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(event_time,$resolutionInterval),\n  count(*),\n  'Total' as metric\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    and event_type='init'\n    and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    and data->'device' ? 'platform'\n    and data->'app' ? $appMetricName\n    and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  GROUP BY time;"
    }
   ]
  },
  {
   "title": "Metrics per $appMetricName [platform: $platform]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Unique clients per $appMetricName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(latestEntryInTimeRange.clientId),\n  (latestEntryInTimeRange.data->'app'->>$appMetricName)::text as metric\nFROM\n    (select entry.clientId, entry.event_time, entry.data \n      from mobileAppMetrics entry \n      inner join \n        (select clientId, max(event_time) as latestEntryTime \n          from mobileAppMetrics \n          where $__timeFilter(event_time) \n            and event_type='init'\n            and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n            and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n          group by clientId\n        ) \n        latestEntry \n        on entry.clientId = latestEntry.clientId and entry.event_time = latestEntryTime\n        where event_type='init'\n      ) latestEntryInTimeRange\n  GROUP by metric;"
    }
   ]
  },
  {
   "title": "App launch count per $appMetricName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(event_time,$resolutionInterval),\n  count(*),\n  (data->'app'->>$appMetricName)::text as metric\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time) \n    and event_type='init'\n    and data->'app' ? $appMetricName\n    and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  GROUP BY metric, time;"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(event_time,$resolutionInterval),\n  count(*),\n  'Total' as metric\nFROM mobileAppMetrics\n  WHERE $__timeFilter(event_time) \n    and event_type='init'\n    and data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    and data->'device' ? 'platform'\n    and data->'app' ? $appMetricName\n    and data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  GROUP BY time;"
    }
   ]
  }
 ]
}