{
 "title": "Mobile Security Metrics 3",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "appId",
    "label": "App",
    "query": "select distinct data->'app'->>'appId' from mobileappmetrics where event_type='security';"
   },
   {
    "name": "platform",
    "label": "Platform",
    "query": "select distinct data->'device'->>'platform' from mobileappmetrics where event_type='security';"
   },
   {
    "name": "checkType",
    "label": "Check Type",
    "query": "select distinct (all_checks.chk->>'name') from (select jsonb_array_elements(data->'security') chk from mobileAppMetrics WHERE $__timeFilter(event_time) AND event_type='security') as all_checks;"
   },
   {
    "name": "resolutionInterval",
    "label": "Resolution",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Introduction",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "content": "# Mobile Security Metrics\n\nThis dashboard shows Self-Defence Security Check results per platform. Select the platform and application using the dropdowns above."
  },
  {
   "title": "Passed check %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  cast((select sum(case when (securityCheck->>'passed')::boolean then 1 else 0 end)) as decimal) / cast(count(*) as decimal) * 100\nFROM\n  (SELECT jsonb_array_elements(data->'security') as securityCheck\n    FROM mobileAppMetrics\n        WHERE $__timeFilter(event_time)\n        AND event_type='security'\n        AND data ? 'security'\n        AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n        AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  ) as checksRaw\nWHERE securityCheck->>'name' like $checkType;"
    }
   ]
  },
  {
   "title": "Check count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM\n  (SELECT jsonb_array_elements(data->'security') as securityCheck\n    FROM mobileAppMetrics\n        WHERE $__timeFilter(event_time)\n        AND event_type='security'\n        AND data ? 'security'\n        AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n        AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  ) as checksRaw\nWHERE securityCheck->>'name' like $checkType;"
    }
   ]
  },
  {
   "title": "Unique clients w/ checks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT clientId)\nFROM\n  (SELECT clientId, jsonb_array_elements(data->'security') as securityCheck\n    FROM mobileAppMetrics\n        WHERE $__timeFilter(event_time)\n        AND event_type='security'\n        AND data ? 'security'\n        AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n        AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  ) as checksRaw\nWHERE securityCheck->>'name' like $checkType;"
    }
   ]
  },
  {
   "title": "Apps w/ checks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT appId)\nFROM\n  (SELECT data->'app'->>'appId' as appId, jsonb_array_elements(data->'security') as securityCheck\n    FROM mobileAppMetrics\n        WHERE $__timeFilter(event_time)\n        AND event_type='security'\n        AND data ? 'security'\n        AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n        AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  ) as checksRaw\nWHERE securityCheck->>'name' like $checkType;"
    }
   ]
  },
  {
   "title": "Fails per check type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  checks.entry->>'name' as checkName,\n  count(*)\nFROM\n(\n  SELECT jsonb_array_elements(data->'security') as entry\n    FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n    AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n) as checks\nWHERE checks.entry->>'passed' = 'false'\n  AND checks.entry->>'name' like $checkType\nGROUP BY checkName;"
    }
   ]
  },
  {
   "title": "Fails per app",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  appId,\n  count(*)\nFROM\n(\n  SELECT data->'app'->>'appId' as appId, jsonb_array_elements(data->'security') as entry\n    FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n    AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n) as checks\nWHERE checks.entry->>'passed' = 'false'\n  AND checks.entry->>'name' like $checkType\nGROUP BY appId;"
    }
   ]
  },
  {
   "title": "Fails per platform",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  platform,\n  count(*)\nFROM\n(\n  SELECT data->'device'->>'platform' as platform, jsonb_array_elements(data->'security') as entry\n    FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n    AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n) as checks\nWHERE checks.entry->>'passed' = 'false'\n  AND checks.entry->>'name' like $checkType\nGROUP BY platform;"
    }
   ]
  },
  {
   "title": "Fails per check type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Fails per app",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Fails per platform",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Totals",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, sum(passed) as passed, sum(not_passed) as not_passed\nfrom (SELECT event_time as time,\n  (select sum(case when (sec->>'passed')::boolean then 1 else 0 end)\n  from jsonb_array_elements(data->'security') as sec) as passed,\n  (select sum(case when (sec->>'passed')::boolean then 0 else 1 end)\n  from jsonb_array_elements(data->'security') as sec) as not_passed\nFROM mobileAppMetrics) as t\nWHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Totals per Platform [App: $appId]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, platform as metric, sum(case when passed then 1 else 0 end) as passed\nfrom (\n  select s.clientId, platform, passed from \n  (\n    select * from (\n      select clientId, jsonb_array_elements(data->'security') as sec\n      FROM mobileAppMetrics\n      where $__timeFilter(event_time)\n    ) as securityRecords,\n    jsonb_to_record(sec) as x(name text, passed boolean)\n  ) AS s\n  INNER JOIN (\n    SELECT DISTINCT clientId, data->'device'->>'platform' as platform\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n  ) as a ON (s.clientId = a.clientId)\n) as t\ngroup by metric"
    },
    {
     "rawSql": "select now() as time, platform || ' not passed' as metric, sum(case when passed then 0 else 1 end) as passed\nfrom (\n  select s.clientId, platform, passed from \n  (\n    select * from (\n      select clientId, jsonb_array_elements(data->'security') as sec\n      FROM mobileAppMetrics\n      where $__timeFilter(event_time)\n    ) as securityRecords,\n    jsonb_to_record(sec) as x(name text, passed boolean)\n  ) AS s\n  INNER JOIN (\n    SELECT DISTINCT clientId, data->'device'->>'platform' as platform\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n  ) as a ON (s.clientId = a.clientId)\n) as t\ngroup by metric"
    }
   ]
  },
  {
   "title": "Top Offending Clients",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "select client, appId as app, appVersion as \"version\", sdkVersion, platformVersion, sum(not_passed) as failed_checks from\n(\n  select s.clientId as client,\n  (\n    select sum(case when (sec->>'passed')::boolean then 0 else 1 end)\n      from jsonb_array_elements(s.data->'security') as sec\n  ) as not_passed,\n  a.*\n  from mobileAppMetrics AS s\n  INNER JOIN (\n    SELECT DISTINCT ON (clientId)\n    clientId,\n    data->'app'->>'appId' as appId,\n    data->'app'->>'appVersion' as appVersion,\n    data->'app'->>'sdkVersion' as sdkVersion,\n    data->'device'->>'platform' as platform,\n    data->'device'->>'platformVersion' as platformVersion\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n    and data->'device'->>'platform' like $platform\n  ) as a ON (s.clientId = a.clientId)\n  WHERE $__timeFilter(s.event_time)\n) as t\ngroup by client, appId, appVersion, sdkVersion, platformVersion\nORDER BY sum(not_passed) DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Totals per Check Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, name as metric, sum(case when passed then 1 else 0 end) as passed\nfrom (\n  select s.clientId, name, passed from \n  (\n    select * from (\n      select clientId, jsonb_array_elements(data->'security') as sec\n      FROM mobileAppMetrics\n      where $__timeFilter(event_time)\n    ) as securityRecords,\n    jsonb_to_record(sec) as x(name text, passed boolean)\n  ) AS s\n  INNER JOIN (\n    SELECT DISTINCT clientId\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n    and data->'device'->>'platform' like $platform\n  ) as a ON (s.clientId = a.clientId)\n) as t\ngroup by metric"
    },
    {
     "rawSql": "select now() as time, name || ' not passed' as metric, sum(case when passed then 0 else 1 end) as passed\nfrom (\n  select s.clientId, name, passed from \n  (\n    select * from (\n      select clientId, jsonb_array_elements(data->'security') as sec\n      FROM mobileAppMetrics\n      where $__timeFilter(event_time)\n    ) as securityRecords,\n    jsonb_to_record(sec) as x(name text, passed boolean)\n  ) AS s\n  INNER JOIN (\n    SELECT DISTINCT clientId\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n    and data->'device'->>'platform' like $platform\n  ) as a ON (s.clientId = a.clientId)\n) as t\ngroup by metric"
    }
   ]
  },
  {
   "title": "Details [Platform: $platform, App: $appId]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "platform"
  },
  {
   "title": "Metrics History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select event_time as time, sum(passed) as passed, sum(not_passed) as not_passed\nfrom (\n  SELECT event_time,\n  (select sum(case when (sec->>'passed')::boolean then 1 else 0 end)\n  from jsonb_array_elements(data->'security') as sec) as passed,\n  (select sum(case when (sec->>'passed')::boolean then 0 else 1 end)\n  from jsonb_array_elements(data->'security') as sec) as not_passed\n  FROM mobileAppMetrics as s\n  INNER JOIN (\n    SELECT DISTINCT clientId\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n    and data->'device'->>'platform' like $platform\n  ) as a ON (s.clientId = a.clientId)\n  where $__timeFilter(event_time)\n) as check_counts\ngroup by event_time"
    }
   ]
  },
  {
   "title": "Details [Platform: $platform, App: $appId]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "title": "Metrics History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select event_time as time, sum(passed) as passed, sum(not_passed) as not_passed\nfrom (\n  SELECT event_time,\n  (select sum(case when (sec->>'passed')::boolean then 1 else 0 end)\n  from jsonb_array_elements(data->'security') as sec) as passed,\n  (select sum(case when (sec->>'passed')::boolean then 0 else 1 end)\n  from jsonb_array_elements(data->'security') as sec) as not_passed\n  FROM mobileAppMetrics as s\n  INNER JOIN (\n    SELECT DISTINCT clientId\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n    and data->'device'->>'platform' like $platform\n  ) as a ON (s.clientId = a.clientId)\n  where $__timeFilter(event_time)\n) as check_counts\ngroup by event_time"
    }
   ]
  }
 ]
}